Repository openshift/cluster-storage-operator, pull requests merged in 2019-04, with the labels that each got.

#25 Add vsphere default storageclass
  assets/vsphere.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
  pkg/generated/bindata.go
Labels: approved, lgtm, size/M

#28 Add azure default storageclass
  assets/azure.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
  pkg/generated/bindata.go
Labels: approved, lgtm, size/M

#29 Replace Failing with Degraded and -Platform with -PlatformType
  Gopkg.lock
  pkg/controller/clusterstorage/clusterstorage_controller.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/type_features.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm, size/XXL

#30 Add node-selector annotation to namespace
  manifests/00-namespace.yaml
Labels: approved, lgtm, size/XS
