Repository openshift/cluster-storage-operator, pull requests merged in 2019-07, with the labels that each got.

#41 Bug 1727044: Set missing Upgradeable condition
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#42 Bug: 1731059: Use topology aware dynamic provisioning in the clouds
  assets/azure.yaml
  assets/openstack.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm, size/XS

#43 Adding the default GCP StorageClass.
  assets/gcp.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
  pkg/generated/bindata.go
Labels: approved, lgtm, size/M
