Repository openshift/cluster-storage-operator, pull requests merged in 2019-03, with the labels that each got.

#16 version: Set the cluster operator version based on the payload
  manifests/02-deployment.yaml
  manifests/03-cluster-operator.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, lgtm, size/S

#17 The cluster storage operator should report the name "storage"
  Dockerfile
  manifests/02-deployment.yaml
  manifests/03-cluster-operator.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, lgtm, size/S

#20 Do not re-queue if error is unsupported
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, lgtm, size/XS

#21 Set versions if unsupported platform but Available
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, lgtm, size/XS

#22 Set progressing status just before trying to create SC
  Gopkg.lock
  pkg/controller/clusterstorage/clusterstorage_controller.go
  pkg/controller/clusterstorage/clusterstorage_controller_test.go
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm, size/XXL

#23 Read Infrastructure instead of cluster-config-v1 configmap
  Gopkg.lock
  Gopkg.toml
  deploy/cluster-config-v1.yaml
  deploy/infrastructure.yaml
  manifests/01-cluster-config-role-binding.yaml
  manifests/01-cluster-config-role.yaml
  manifests/01-cluster-role.yaml
  pkg/controller/clusterstorage/clusterstorage_controller.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/asset/store/data
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/installconfig_libvirt.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/none/doc.go
  vendor/github.com/openshift/installer/pkg/types/none/platform.go
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/library-go/pkg/controller/ownerref.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, lgtm, size/XXL
