Repository openshift/cluster-storage-operator, pull requests merged in 2019-06, with the labels that each got.

#34 Enable AWS EBS volume expansion by default
  assets/aws.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm, size/XS

#37 Add related objects to status
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: approved, lgtm, size/S

#39 Revert "[release-4.1] Bug 1717640: Add related objects to Status"
  pkg/controller/clusterstorage/clusterstorage_controller.go
Labels: bugzilla/valid-bug
