Repository openshift/cluster-storage-operator, pull requests merged in 2020-08, with the labels that each got.

#68 Move to openshift-manila-csi-driver namespace
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/manila/09_credentials.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#67 Fix NFS driver deployment
  manifests/04_deployment.yaml
Labels: approved, lgtm

#70 Bug 1865797: Fix related namespaces
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#69 Bug 1862523: Add migration controller
  pkg/operator/csidriveroperator/csioperatorclient/aws.go
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
  pkg/operator/csidriveroperator/csioperatorclient/types.go
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/driverstarter.go
  pkg/operator/csidriveroperator/olmremovalcontroller.go
  pkg/operatorclient/operatorclient.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#71 Bug 1865769: Remove authentication rolebinding
  manifests/01_operator_namespace.yaml
  manifests/01_role_binding_authentication_reader.yaml
  manifests/02_cluster_csi_driver_crd.yaml
  manifests/03_crd_operator.yaml
  manifests/04_operator_cr.yaml
  manifests/05_service_account.yaml
  manifests/06_operator_rbac.yaml
  manifests/07_deployment.yaml
  manifests/08_cluster_operator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#73 Bug 1867704: Give pod listing permissions to aws operator
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#74 Bug 1867735: Sync RBAC rules from Manila operator
  assets/csidriveroperators/manila/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#75 Bug 1867735: Fix syncing of Manila CA certificate
  pkg/csoclients/csoclients.go
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#76 Bug 1866262: Remove DriverConfig from CSI operator CRs
  assets/csidriveroperators/aws-ebs/08_cr.yaml
  assets/csidriveroperators/manila/08_cr.yaml
  assets/csidriveroperators/ovirt/08_cr.yaml
  go.mod
  go.sum
  manifests/02_cluster_csi_driver_crd.yaml
  pkg/generated/bindata.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/quota/v1/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#77 Bug 1869516: Prevent crash if PlatformStatus is nil
  pkg/operator/defaultstorageclass/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#78 Bug 1871051: Add CSI operators permissions to patch volumeattachment/status
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#81 Bug 1873175: Allow CSI Drivers to run on master nodes
  assets/csidriveroperators/aws-ebs/07_deployment.yaml
  assets/csidriveroperators/manila/07_deployment.yaml
  assets/csidriveroperators/ovirt/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#80 Bug 1868339: Move CredentialsRequest creation to CSO
  manifests/02_csi_driver_operators_namespace.yaml
  manifests/03_credentials_request_aws.yaml
  manifests/03_credentials_request_openstack.yaml
  manifests/03_credentials_request_ovirt.yaml
  manifests/04_cluster_csi_driver_crd.yaml
  manifests/05_crd_operator.yaml
  manifests/06_operator_cr.yaml
  manifests/07_service_account.yaml
  manifests/08_operator_rbac.yaml
  manifests/09_deployment.yaml
  manifests/10_cluster_operator.yaml
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
  pkg/operator/csidriveroperator/csioperatorclient/ovirt.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
