Repository openshift/cluster-storage-operator, pull requests merged in 2020-11, with the labels that each got.

#95 Updating cluster-storage-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#99 Remove OpenStack Cinder operator startup
  assets/csidriveroperators/openstack-cinder/01_namespace.yaml
  assets/csidriveroperators/openstack-cinder/02_sa.yaml
  assets/csidriveroperators/openstack-cinder/03_role.yaml
  assets/csidriveroperators/openstack-cinder/04_rolebinding.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/06_clusterrolebinding.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/08_cr.yaml
  manifests/03_credentials_request_cinder.yaml
  manifests/03_credentials_request_openstack.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/cinder.go
  pkg/operator/starter.go
Labels: approved, lgtm

#100 Bug 1894025: Add annotations to cluster-csi-drivers namespace
  assets/csidriveroperators/aws-ebs/01_namespace.yaml
  assets/csidriveroperators/manila/01_namespace.yaml
  assets/csidriveroperators/ovirt/01_namespace.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#101 Add GCP-PD CSI Operator to CSO
  assets/csidriveroperators/gcp-pd/01_namespace.yaml
  assets/csidriveroperators/gcp-pd/02_sa.yaml
  assets/csidriveroperators/gcp-pd/03_role.yaml
  assets/csidriveroperators/gcp-pd/04_rolebinding.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/06_clusterrolebinding.yaml
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/gcp-pd/08_cr.yaml
  go.mod
  go.sum
  manifests/03_credentials_request_gcp.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/gcp-pd.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/OWNERS
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/oauth/v1/generated.pb.go
  vendor/github.com/openshift/api/oauth/v1/generated.proto
  vendor/github.com/openshift/api/oauth/v1/register.go
  vendor/github.com/openshift/api/oauth/v1/types.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/oauth/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/samples/v1/0000_10_samplesconfig.crd.yaml
  vendor/github.com/openshift/api/samples/v1/types_config.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/modules.txt
Labels: approved, lgtm

#103 Add OpenStack Cinder driver startup
  assets/csidriveroperators/openstack-cinder/01_namespace.yaml
  assets/csidriveroperators/openstack-cinder/02_sa.yaml
  assets/csidriveroperators/openstack-cinder/03_role.yaml
  assets/csidriveroperators/openstack-cinder/04_rolebinding.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/06_clusterrolebinding.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/08_cr.yaml
  manifests/03_credentials_request_cinder.yaml
  manifests/03_credentials_request_manila.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/cinder.go
  pkg/operator/starter.go
Labels: approved, lgtm

#104 Bug 1902552: Fix cinder-csi images
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
