Repository openshift/cluster-storage-operator, pull requests merged in 2020-10, with the labels that each got.

#89 Bug 1879365: Move CSO namespace to lower runlevel
  manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
  manifests/01_operator_namespace.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#94 Bump OpenShift API to include Cinder CSI driver
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm

#96 Bug 1882394: UPSTREAM: <carry>: operator-sdk: return error if lock is not leader-for-life
  Gopkg.toml
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#97 add current profile annotations to CVO manifests
  manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  manifests/03_credentials_request_aws.yaml
  manifests/03_credentials_request_openstack.yaml
  manifests/03_credentials_request_ovirt.yaml
  manifests/06_operator_cr.yaml
  manifests/07_service_account.yaml
  manifests/08_operator_rbac.yaml
  manifests/09_deployment.yaml
  manifests/10_cluster_operator.yaml
Labels: approved, lgtm

#98 Add OpenStack Cinder driver startup
  assets/csidriveroperators/openstack-cinder/01_namespace.yaml
  assets/csidriveroperators/openstack-cinder/02_sa.yaml
  assets/csidriveroperators/openstack-cinder/03_role.yaml
  assets/csidriveroperators/openstack-cinder/04_rolebinding.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/06_clusterrolebinding.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/08_cr.yaml
  manifests/03_credentials_request_cinder.yaml
  manifests/03_credentials_request_manila.yaml
  manifests/09_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/cinder.go
  pkg/operator/starter.go
Labels: approved, lgtm
