Repository openshift/cluster-storage-operator, pull requests merged in 2020-12, with the labels that each got.

#105 Add missing default profile annotation
  manifests/03_credentials_request_gcp.yaml
Labels: approved, lgtm

#108 Bug 1902601: Fix resources in cinder csi deployment template
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#112 aws: grant ebs operator permission to read configmaps
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#110 Add YAMLs for starting vsphere-problem-detector as a deployment
  manifests/03_credentials_request_vsphere.yaml
  manifests/09_deployment.yaml
  manifests/image-references
Labels: approved, lgtm

#107 Bug 1904578: Configure metrics scraping
  manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-storage-operator_02_servicemonitor.yaml
  manifests/06_operator_cr.yaml
  manifests/09_metrics_service.yaml
  manifests/10_deployment.yaml
  manifests/11_cluster_operator.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#117 Bug 1907329: Add missing default cluster profile annotation
  manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml
  manifests/03_credentials_request_vsphere.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
