Repository openshift/cluster-storage-operator, pull requests merged in 2021-01, with the labels that each got.

#120 Bug 1914119: Add RBAC for status field
  assets/vsphere_problem_detector/04_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#118 Bug 1907812: Use separate RBAC objects for AWS CA bundle retrieval
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/07_role_aws_config.yaml
  assets/csidriveroperators/aws-ebs/08_rolebinding_aws_config.yaml
  assets/csidriveroperators/aws-ebs/09_deployment.yaml
  assets/csidriveroperators/aws-ebs/10_cr.yaml
  pkg/csoclients/csoclients.go
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/aws.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#121 Bug 1912945: Add RBAC rules to read proxy resource
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#106 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
  manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-storage-operator_02_servicemonitor.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  manifests/03_credentials_request_aws.yaml
  manifests/03_credentials_request_cinder.yaml
  manifests/03_credentials_request_gcp.yaml
  manifests/03_credentials_request_manila.yaml
  manifests/03_credentials_request_ovirt.yaml
  manifests/03_credentials_request_vsphere.yaml
  manifests/06_operator_cr.yaml
  manifests/07_service_account.yaml
  manifests/08_operator_rbac.yaml
  manifests/09_metrics_service.yaml
  manifests/10_deployment.yaml
  manifests/11_cluster_operator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#123 Bug 1914451: Run CSO as non-root user
  manifests/10_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#126 Bug 1904503: Add prometheus alerts for vsphere
  assets/vsphere_problem_detector/12_prometheusrules.yaml
  go.mod
  pkg/generated/bindata.go
  pkg/operator/vsphereproblemdetector/monitoring.go
  pkg/operator/vsphereproblemdetector/monitoring_test.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#127 Bug 1912945: Add RBAC to allow operator to update CR's spec
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#128 Bug 1917551: Change metric used in alerts for vsphere problem detector
  assets/vsphere_problem_detector/12_prometheusrules.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#131 Bug 1910581: CSO shouldn't overwrite clustercsidriver objects
  pkg/operator/csidriveroperator/crcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#132 [release-4.6] Bug 1921599: Add annotations to cluster-csi-drivers namespace
  assets/csidriveroperators/aws-ebs/01_namespace.yaml
  assets/csidriveroperators/manila/01_namespace.yaml
  assets/csidriveroperators/ovirt/01_namespace.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
