Repository openshift/cluster-storage-operator, pull requests merged in 2021-09, with the labels that each got.

#208 Bug 1999853: ControlPlaneTopology: Fix node selector for CSI driver operator deployment
  pkg/operator/csidriveroperator/csioperatorclient/types.go
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/driverstarter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#206 Bug 1992875: Add azure credentials
  assets/csidriveroperators/azure-disk/08_deployment.yaml
  manifests/03_credentials_request_azure.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#209 Bug 1999674: Update prometheus rule to alert about esxi host versions
  assets/vsphere_problem_detector/12_prometheusrules.yaml
  pkg/dependencymagnet/dependencymagnet.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#210 Bug 1996672: Add proxy support to cinder CSI
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#214 Install Azure Disk CSI Driver by default
  pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
Labels: approved, lgtm

#217 Install vSphere CSI Driver and Operator by default
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
Labels: approved, lgtm
