Repository openshift/cluster-storage-operator, pull requests merged in 2021-11, with the labels that each got.

#229 Update Shared Resource Operator permissions
  assets/csidriveroperators/shared-resource/05_clusterrole.yaml
Labels: approved, lgtm

#230 Credential Request added
  manifests/03_credentials_request_ibm.yaml
Labels: approved, lgtm, ok-to-test

#231 Migrate additional yaml files from SRO repository
  assets/csidriveroperators/shared-resource/11_metrics_service.yaml
  assets/csidriveroperators/shared-resource/12_servicemonitor.yaml
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
  pkg/operator/csidriveroperator/csioperatorclient/types.go
  pkg/operator/csidriveroperator/driverstarter.go
Labels: approved, lgtm

#215 Bug 2001761: Fix RelatedObjects when RBAC API is missing
  pkg/csoclients/csoclients.go
  pkg/operator/csidriveroperator/driverstarter.go
  pkg/operator/csidriveroperator/driverstarter_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#237 Secure metrics for Shared Resource Operator
  assets/csidriveroperators/shared-resource/11_metrics_service.yaml
  assets/csidriveroperators/shared-resource/12_servicemonitor.yaml
Labels: approved, lgtm

#238 Add CredentialsRequest for Alibaba Disk CSI driver
  manifests/03_credentials_request_alibaba.yaml
Labels: approved, lgtm

#240 Replace registry.ci images with quay
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
Labels: approved, lgtm

#239 Add Alibaba Disk CSI driver
  assets/csidriveroperators/alibaba-disk/02_sa.yaml
  assets/csidriveroperators/alibaba-disk/03_role.yaml
  assets/csidriveroperators/alibaba-disk/04_rolebinding.yaml
  assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
  assets/csidriveroperators/alibaba-disk/06_clusterrolebinding.yaml
  assets/csidriveroperators/alibaba-disk/07_deployment.yaml
  assets/csidriveroperators/alibaba-disk/08_cr.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/alibaba-disk.go
  pkg/operator/starter.go
Labels: approved, lgtm

#241 Bug 2027363: Fix reference to Azure File images
  manifests/image-references
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
