Repository openshift/cluster-storage-operator, pull requests merged in 2021-04, with the labels that each got.

#145 Prepare for metrics collection in CSI driver operators
  assets/csidriveroperators/aws-ebs/01_namespace.yaml
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/01_namespace.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/manila/01_namespace.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/01_namespace.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/01_namespace.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/aws.go
  pkg/operator/csidriveroperator/csioperatorclient/cinder.go
  pkg/operator/csidriveroperator/csioperatorclient/gcp-pd.go
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
  pkg/operator/csidriveroperator/csioperatorclient/ovirt.go
Labels: approved, lgtm

#148 Add AzureDisk CSI driver installation
  assets/csidriveroperators/azure-disk/03_sa.yaml
  assets/csidriveroperators/azure-disk/04_role.yaml
  assets/csidriveroperators/azure-disk/05_rolebinding.yaml
  assets/csidriveroperators/azure-disk/06_clusterrole.yaml
  assets/csidriveroperators/azure-disk/07_clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/08_deployment.yaml
  assets/csidriveroperators/azure-disk/09_cr.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
  pkg/operator/starter.go
Labels: approved, lgtm

#151 Pass KUBE_RBAC_PROXY_IMAGE to CSI driver operators
  assets/csidriveroperators/aws-ebs/09_deployment.yaml
  assets/csidriveroperators/azure-disk/08_deployment.yaml
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/manila/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/ovirt/07_deployment.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/util.go
Labels: approved, lgtm

#154 Add TokenReview permissions to newly introduced operators
  assets/csidriveroperators/azure-disk/06_clusterrole.yaml
  assets/csidriveroperators/vsphere/06_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#152 Degrade the cluster when an unsupported CSI driver is already installed
  pkg/operator/csidriveroperator/driverstarter.go
  pkg/operator/csidriveroperator/driverstarter_test.go
Labels: approved, lgtm

#153 Add vsphere syncer deployment
  assets/csidriveroperators/vsphere/08_deployment.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
Labels: approved, lgtm

#150 Add management workload annotations
  assets/csidriveroperators/aws-ebs/09_deployment.yaml
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/manila/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/ovirt/07_deployment.yaml
  assets/csidriveroperators/vsphere/08_deployment.yaml
  manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  manifests/10_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#149 Remove "vmware" prefix from CSI operator and driver
  manifests/10_deployment.yaml
  manifests/image-references
Labels: approved, lgtm

#155 Bug 1949041: Update image-references for vsphere
  manifests/image-references
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#161 Bug 1949554: Pass KUBE_RBAC_PROXY to vSphere CSI driver operator
  assets/csidriveroperators/vsphere/08_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#158 Bug 1948448: Add log level to vSphere operator
  assets/csidriveroperators/vsphere/08_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#159 Bug 1947866: Add log level to Azure Disk CSI Operator
  assets/csidriveroperators/azure-disk/08_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#162 Bug 1949357: Allow Manila operator to create ServiceMonitor in the driver namespace
  assets/csidriveroperators/manila/03_role.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#157 Bug 1947360: vSphere: set CPU/memory resource request
  assets/csidriveroperators/vsphere/08_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#146 Bug 1948721: IBM Cloud manifest profile patch
  .gitignore
  Makefile
  go.mod
  go.sum
  manifests/10_deployment-ibm-cloud-managed.yaml
  profile-patches/ibm-cloud-managed/10_deployment.yaml-patch
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#156 Bug 1948505: Add missing RBAC rules for vSphere
  assets/csidriveroperators/vsphere/06_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#163 Bug 1949357: Add missing RBAC rules to Manila operator
  assets/csidriveroperators/manila/05_clusterrole.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#164 Rename workload annotations
  assets/csidriveroperators/aws-ebs/09_deployment.yaml
  assets/csidriveroperators/azure-disk/08_deployment.yaml
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/manila/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/ovirt/07_deployment.yaml
  assets/csidriveroperators/vsphere/08_deployment.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm
