Repository openshift/cluster-storage-operator, pull requests merged in 2021-02, with the labels that each got.

#133 Bug 1883538: Only include the relevant drivers in relatedObjects
  pkg/operator/csidriveroperator/driverstarter.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#134 Bug 1923098: Add replicasets to vsphere permissions
  assets/vsphere_problem_detector/02_role.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#129 vsphere: don't redeploy StorageClass in every sync
  assets/storageclasses/vsphere.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#116 Fix typo in README.md
  README.md
Labels: approved, lgtm

#138 Propagate log level to GCE and Cinder CSI driver operators
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm
