Repository openshift/cluster-storage-operator, pull requests merged in 2021-05, with the labels that each got.

#165 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#166 Bug 1943719: Add alert about vsphere-problem-detector unable to connect
  assets/vsphere_problem_detector/12_prometheusrules.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#168 Bug 1961538: manifests: remove namespace from cluster-storage-operator-role binding
  manifests/08_operator_rbac.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#141 Bug 1936871: Add volumes with credentials to Cinder operator deployment
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#167 Bug 1961120: added permissions to service monitoring
  assets/csidriveroperators/aws-ebs/03_role.yaml
  assets/csidriveroperators/azure-disk/04_role.yaml
  assets/csidriveroperators/gcp-pd/03_role.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/03_role.yaml
  assets/csidriveroperators/ovirt/03_role.yaml
  assets/csidriveroperators/vsphere/04_role.yaml
  assets/vsphere_problem_detector/02_role.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
