Repository openshift/cluster-storage-operator, pull requests merged in 2021-12, with the labels that each got.

#242 Add IBM VPC Block CSI Driver Operator
  assets/csidriveroperators/ibm-vpc-block/03_sa.yaml
  assets/csidriveroperators/ibm-vpc-block/04_role.yaml
  assets/csidriveroperators/ibm-vpc-block/05_rolebinding.yaml
  assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml
  assets/csidriveroperators/ibm-vpc-block/07_clusterrolebinding.yaml
  assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
  assets/csidriveroperators/ibm-vpc-block/09_cr.yaml
  go.mod
  go.sum
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/ibm-vpc-block.go
  pkg/operator/starter.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: approved, lgtm

#243 Bug 2030364: Setup port, mount TLS cert into CSI shared resource operator
  assets/csidriveroperators/shared-resource/09_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#246 Remove invalid -v argument from IBM VPC operator deployment
  assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
Labels: approved, lgtm

#247 bug 2034515: fix: pull in latest library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#249 [4.8] Bug 2034270: Add trusted CA bundle to vsphere operators
  assets/csidriveroperators/vsphere/02_configmap.yaml
  assets/csidriveroperators/vsphere/08_deployment.yaml
  assets/vsphere_problem_detector/06_configmap.yaml
  assets/vsphere_problem_detector/07_deployment.yaml
  go.mod
  go.sum
  pkg/dependencymagnet/dependencymagnet.go
  pkg/generated/bindata.go
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
  pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go
  pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#250 Bug 2033111: IBM VPC operator library bump removed global CLI args
  assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#248 [4.7] Bug 2030740: Add trusted CA bundle to vsphere operators
  assets/vsphere_problem_detector/06_configmap.yaml
  assets/vsphere_problem_detector/07_deployment.yaml
  pkg/dependencymagnet/dependencymagnet.go
  pkg/generated/bindata.go
  pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go
  pkg/operator/vsphereproblemdetector/vsphere_problem_detector_starter.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed
