Repository openshift/cluster-storage-operator, pull requests merged in 2022-10, with the labels that each got.

#317 STOR-858: Bump github.com/openshift/* and k8s.io/*
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#321 Bump go to 1.19
  .ci-operator.yaml
  Dockerfile
  pkg/operator/csidriveroperator/olmremovalcontroller.go
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/snapshotcrd/controller.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#303 [CNF-5645] add storage capability annotation
  manifests/0000_49_cluster-storage-operator_01_operator_namespace.yaml
  manifests/0000_90_cluster-storage-operator_01_prometheusrbac.yaml
  manifests/0000_90_cluster-storage-operator_02_servicemonitor.yaml
  manifests/02_csi_driver_operators_namespace.yaml
  manifests/03_credentials_request_alibaba.yaml
  manifests/03_credentials_request_aws.yaml
  manifests/03_credentials_request_azure.yaml
  manifests/03_credentials_request_azure_file.yaml
  manifests/03_credentials_request_cinder.yaml
  manifests/03_credentials_request_gcp.yaml
  manifests/03_credentials_request_ibm.yaml
  manifests/03_credentials_request_manila.yaml
  manifests/03_credentials_request_ovirt.yaml
  manifests/03_credentials_request_powervs.yaml
  manifests/03_credentials_request_vsphere_csi.yaml
  manifests/03_credentials_request_vsphere_detector.yaml
  manifests/06_operator_cr.yaml
  manifests/07_service_account.yaml
  manifests/08_operator_rbac.yaml
  manifests/09_metrics_service.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/11_cluster_operator.yaml
  manifests/12_prometheusrules.yaml
  profile-patches/ibm-cloud-managed/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#323 OCPBUGS-1904: Allow CSI operator to get CRDs
  assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/azure-disk/06_clusterrole.yaml
  assets/csidriveroperators/azure-file/06_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  assets/csidriveroperators/powervs-block/04_clusterrole.yaml
  assets/csidriveroperators/shared-resource/05_clusterrole.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-critical, jira/valid-bug

#316 Remove specific UID from cluster-storage-operator
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#322 OCPBUGS-1361: Reword vSphere problem detector check alerts
  assets/vsphere_problem_detector/12_prometheusrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-low, jira/valid-bug

#324 Bug 2093016: Add alert about attach / mount failing
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#314 OCPBUGS-691: [release-4.10] correct sc error messages for ibm and alibaba platforms
  pkg/operator/defaultstorageclass/controller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#325 OCPBUGS-2880: Fix panic on empty featureGate.spec.customNoUpgrade
  pkg/operator/csidriveroperator/driverstarter.go
  pkg/operator/csidriveroperator/driverstarter_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug
