Repository openshift/cluster-storage-operator, pull requests merged in 2022-01, with the labels that each got.

#252 Bug 2038389: Union upgradeable conditions as well from ClusterCSIDriver objects
  pkg/operator/csidriveroperator/crcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#251 Bug 1961317: Add operator's ClusterRoleBinding to RelatedObjects
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#254 Bug 2040880: Do not replace unknown condition with true when we union conditions
  pkg/operator/csidriveroperator/crcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#256 Bug 2043130: Update CSI sidecars to the latest release for 4.10
  assets/csidriveroperators/aws-ebs/05_clusterrole.yaml
  assets/csidriveroperators/azure-disk/06_clusterrole.yaml
  assets/csidriveroperators/azure-file/06_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  assets/csidriveroperators/shared-resource/05_clusterrole.yaml
  assets/csidriveroperators/vsphere/06_clusterrole.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#258 Bug 2045112: Add leases rbac for vsphere-problem-detector
  assets/vsphere_problem_detector/04_clusterrole.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#259 Bug 2047025: Add "patch" permissions to Alibaba CSI driver operator
  assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#257 Bug 2044481: update ClusterOperator relatedObjects to collect sharedresource CRD instances
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
