Repository openshift/cluster-storage-operator, pull requests merged in 2022-05, with the labels that each got.

#274 manifests/deployment: comply to restricted pod security level
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
Labels: approved, lgtm

#273 Bug 2077050: OCP should default to pd-ssd disk type on GCP
  assets/storageclasses/gcp.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#279 Bug 2077599: Alert on vCenter < 7.0.2
  assets/vsphere_problem_detector/12_prometheusrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#283 Bug 2077050: Revert "OCP should default to pd-ssd disk type on GCP"
  assets/storageclasses/gcp.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#278 Bug 2086231: BUILD-405: Install the Shared Resource CSI Driver WebHook
  assets/csidriveroperators/shared-resource/09_deployment.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#287 Bug 2088533: remove unused '-v' for shared resource operator as part of klogv2/openshift api/ k8s bump
  assets/csidriveroperators/shared-resource/09_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#277 Bug 2081557: Fix DefaultStorageClassController getting Available=False on error
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/defaultstorageclass/controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
