Repository openshift/cluster-storage-operator, pull requests merged in 2022-08, with the labels that each got.

#305 Bug 2108054: Add alert about unsupported CSI driver
  assets/csidriveroperators/vsphere/13_prometheusrules.yaml
  go.mod
  go.sum
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
  pkg/operator/csidriveroperator/driverstarter.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/images.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#307 STOR-956: Bump(openshift/api): to get CSI changes
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
  vendor/github.com/openshift/api/helm/v1beta1/types_project_helm_chart_repository.go
  vendor/github.com/openshift/api/helm/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/00_imageregistry.crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/types.go
  vendor/github.com/openshift/api/kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_vsphereprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/test-route-validation.sh
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#298 Bug 2102576: DefaultStorageClassController reports fake message on azure and openstack
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/defaultstorageclass/controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#308 Bug 2108054: Allow Prometheus to scan openshift-cluster-csi-drivers namespace
  assets/csidriveroperators/vsphere/13_prometheus_role.yaml
  assets/csidriveroperators/vsphere/14_prometheus_rolebinding.yaml
  assets/csidriveroperators/vsphere/15_prometheusrules.yaml
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#304 Add PowerVS Block CSI Driver Operator
  assets/csidriveroperators/powervs-block/01_sa.yaml
  assets/csidriveroperators/powervs-block/02_role.yaml
  assets/csidriveroperators/powervs-block/03_rolebinding.yaml
  assets/csidriveroperators/powervs-block/04_clusterrole.yaml
  assets/csidriveroperators/powervs-block/05_clusterrolebinding.yaml
  assets/csidriveroperators/powervs-block/06_deployment.yaml
  assets/csidriveroperators/powervs-block/07_cr.yaml
  manifests/03_credentials_request_powervs.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/ibm-cloud-managed-cleanup.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/powervs-block.go
  pkg/operator/starter.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#310 Bug 2112237: correct sc error messages for ibm and alibaba platforms
  pkg/operator/defaultstorageclass/controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
