Repository openshift/cluster-storage-operator, pull requests merged in 2023-08, with the labels that each got.

#390 Remove "get" verb from "events" resource of RBAC for provisioner sidecar
  manifests/09_sidecar-main_provisioner_role.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#391 OCPBUGS-17356: Fix PodStartupStorageOperationsFailing alert
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#392 STOR-1432: hypershift: add independent refs for AWS EBS driver controller images
  manifests/10_deployment-hypershift.yaml
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#393 STOR-1432: hypershift: pass through control plane images to AWS EBS CSI driver operator
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  pkg/operator/csidriveroperator/csioperatorclient/aws.go
  pkg/operator/csidriveroperator/util.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#388 STOR-1274: use granular permissons for Azure credential requests
  manifests/03_credentials_request_azure.yaml
  manifests/03_credentials_request_azure_file.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
