Repository openshift/cluster-storage-operator, pull requests merged in 2023-06, with the labels that each got.

#380 OCPBUGS-13187: Make vsphere-problem-detector alerts configurable
  go.mod
  pkg/operator/vsphereproblemdetector/config.go
  pkg/operator/vsphereproblemdetector/config_test.go
  pkg/operator/vsphereproblemdetector/monitoring.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#364 CCO-319: Add serviceAccountNames to azure-disk and azure-file credentials
  manifests/03_credentials_request_azure.yaml
  manifests/03_credentials_request_azure_file.yaml
Labels: approved, lgtm, jira/valid-reference

#369 STOR-1167: Add permissions needed by fast snapshots to AWS CSI driver
  manifests/03_credentials_request_aws.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#379 STOR-1065: Publish ClusterRoles for csi driver sidecars
  manifests/openshift-csi-provisioner-configmap-and-secret-reader-role.yaml
  manifests/openshift-csi-provisioner-volumeattachment-reader-role.yaml
  manifests/openshift-csi-provisioner-volumesnapshot-reader-role.yaml
  manifests/openshift-csi-resizer-infrastructure-reader-role.yaml
  manifests/openshift-csi-resizer-storageclass-reader-role.yaml
  manifests/sidecar-main_attacher_role.yaml
  manifests/sidecar-main_provisioner_role.yaml
  manifests/sidecar-main_resizer_role.yaml
  manifests/sidecar-main_snapshotter_role.yaml
Labels: approved, lgtm, px-approved, docs-approved, jira/valid-reference

#382 OCPBUGS-14053: decrease severity for MultipleDefaultStorageClasses alert
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#371 OCPBUGS-13696: Warn about CBT enabled VMs via vsphere-problem-detector
  assets/vsphere_problem_detector/12_prometheusrules.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
