Repository openshift/cluster-storage-operator, pull requests merged in 2023-04, with the labels that each got.

#353 OCPBUGS-11112: Add missing workload label to openshift-manila-csi-driver NS
  assets/csidriveroperators/manila/01_namespace.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#350 OCPBUGS-8683: Add management workloads annotations
  assets/vsphere_problem_detector/07_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#355 [4.12] OCPBUGS-10646: Hypershift: set control plane operand properties
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/01_operator_role.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml
  pkg/csoclients/csoclients.go
  pkg/csoclients/fake.go
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/hypershift_deployment_controller.go
  pkg/operator/vsphereproblemdetector/vsphere_problem_detector_deployment.go
  pkg/utils/deployment_controller.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
  vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
  vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#360 OCPBUGS-11729: VSphereStorageDriver does not document the platform default
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
