Repository openshift/cluster-storage-operator, pull requests merged in 2023-11, with the labels that each got.

#415 STOR-1453: Grant permissions to access `apiserver` to CSI driver operators
  assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/base/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-disk/06_clusterrole.yaml
  assets/csidriveroperators/azure-file/06_clusterrole.yaml
  assets/csidriveroperators/gcp-pd/05_clusterrole.yaml
  assets/csidriveroperators/ibm-vpc-block/06_clusterrole.yaml
  assets/csidriveroperators/manila/05_clusterrole.yaml
  assets/csidriveroperators/openstack-cinder/05_clusterrole.yaml
  assets/csidriveroperators/ovirt/05_clusterrole.yaml
  assets/csidriveroperators/powervs-block/hypershift/guest/04_clusterrole.yaml
  assets/csidriveroperators/powervs-block/standalone/04_clusterrole.yaml
  assets/csidriveroperators/vsphere/06_clusterrole.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#417 OCPBUGS-23120: [IBM ROKS] cluster-storage-operator does not set upgradeable=True
  pkg/operator/csidriveroperator/driver_starter.go
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#419 [release-4.14] OCPBUGS-23210: [IBM ROKS] cluster-storage-operator does not set upgradeable=True
  pkg/operator/csidriveroperator/driver_starter.go
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#425 OCPBUGS-24027: forbidden access to resource on shared-resource-csi-driver-operator
  assets/csidriveroperators/shared-resource/standalone/05_clusterrole.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
