Repository openshift/cluster-storage-operator, pull requests merged in 2023-03, with the labels that each got.

#338 STOR-875: Implement custom keys in AWS EBS CSI driver operator
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#342 BUILD-571: enable shared resource operator to run in an hypershift guest cluster
  assets/csidriveroperators/shared-resource/hypershift/guest/10_cr.yaml
  assets/csidriveroperators/shared-resource/hypershift/mgmt/02_sa.yaml
  assets/csidriveroperators/shared-resource/hypershift/mgmt/09_deployment.yaml
  assets/csidriveroperators/shared-resource/standalone/02_sa.yaml
  assets/csidriveroperators/shared-resource/standalone/03_role.yaml
  assets/csidriveroperators/shared-resource/standalone/04_rolebinding.yaml
  assets/csidriveroperators/shared-resource/standalone/05_clusterrole.yaml
  assets/csidriveroperators/shared-resource/standalone/06_clusterrolebinding.yaml
  assets/csidriveroperators/shared-resource/standalone/07_role_config.yaml
  assets/csidriveroperators/shared-resource/standalone/08_rolebinding_config.yaml
  assets/csidriveroperators/shared-resource/standalone/09_deployment.yaml
  assets/csidriveroperators/shared-resource/standalone/10_cr.yaml
  assets/csidriveroperators/shared-resource/standalone/11_metrics_service.yaml
  assets/csidriveroperators/shared-resource/standalone/12_servicemonitor.yaml
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
  pkg/operator/starter.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#346 OCPBUGS-8328: assets: csi: hypershift: add pull-secret to aws-ebs-csi-driver-operator ServiceAccount
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/02_sa.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#352 OCPBUGS-8691: Hypershift: set control plane operand properties
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/01_operator_role.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml
  pkg/csoclients/csoclients.go
  pkg/csoclients/fake.go
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/hypershift_deployment_controller.go
  pkg/utils/deployment_controller.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference
