Repository openshift/cluster-storage-operator, pull requests merged in 2023-02, with the labels that each got.

#336 OCPBUGS-7300: hypershift: remove inject-proxy annotation from aws-ebs-csi-driver-operator deployment
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/09_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#335 BUILD-407: remove tech preview feature gate for shared resources
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
  pkg/operator/csidriveroperator/driverstarter_standalone_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#332 STOR-1128: Remove defaultstorageclass controller
  assets/storageclasses/vsphere.yaml
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/defaultstorageclass/controller_test.go
  pkg/operator/hypershift_starter.go
  pkg/operator/standalone_starter.go
  pkg/operator/starter.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#339 OCPBUGS-7483: Revert "Merge pull request #332 from bertinatto/default-sc"
  assets/storageclasses/vsphere.yaml
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/defaultstorageclass/controller_test.go
  pkg/operator/hypershift_starter.go
  pkg/operator/standalone_starter.go
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#340 STOR-1128: Stop creating an in-tree SC for vSphere
  assets/storageclasses/vsphere.yaml
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/defaultstorageclass/controller_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#334 STOR-1123: Add alert about topology misconfiguration
  assets/csidriveroperators/vsphere/15_prometheusrules.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#344 OCPBUGS-6992: Add UID to CSO Pod to be able to run with custom SCCs
  manifests/10_deployment-hypershift.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#343 BUILD-407: Revert "remove tech preview feature gate for shared resources"
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
  pkg/operator/csidriveroperator/driverstarter_standalone_test.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#345 OCPBUGS-5410: add ReEncrypt KMS permissions
  manifests/03_credentials_request_aws.yaml
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
