Repository openshift/cluster-storage-operator, pull requests merged in 2024-01, with the labels that each got.

#436 OCPBUGS-22422: Fix PodStartupStorageOperationsFailing alert
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#430 OCPBUGS-22994: Add UsernameWithoutDomain as a reason for triggering VSphereOpenshitConnectionFailure alert
  assets/vsphere_problem_detector/12_prometheusrules.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#437 STOR-1714: Release leadership on SIGTERM
  pkg/operator/operator_starter.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#420 STOR-1722: Azure disk hypershift
  Makefile
  assets/csidriveroperators/azure-disk-original/03_sa.yaml
  assets/csidriveroperators/azure-disk-original/04_role.yaml
  assets/csidriveroperators/azure-disk-original/05_rolebinding.yaml
  assets/csidriveroperators/azure-disk-original/06_clusterrole.yaml
  assets/csidriveroperators/azure-disk-original/07_clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk-original/08_deployment.yaml
  assets/csidriveroperators/azure-disk-original/09_cr.yaml
  assets/csidriveroperators/azure-disk-original/kustomization.yaml
  assets/csidriveroperators/azure-disk/base/03_sa.yaml
  assets/csidriveroperators/azure-disk/base/04_role.yaml
  assets/csidriveroperators/azure-disk/base/05_rolebinding.yaml
  assets/csidriveroperators/azure-disk/base/06_clusterrole.yaml
  assets/csidriveroperators/azure-disk/base/07_clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/base/08_deployment.yaml
  assets/csidriveroperators/azure-disk/base/09_cr.yaml
  assets/csidriveroperators/azure-disk/base/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/claim_role.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_role_azure-disk-csi-driver-operator-role.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_rolebinding_azure-disk-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/v1_serviceaccount_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/monitoring_role.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/03sa.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_role_azure-disk-csi-driver-operator-role.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_rolebinding_azure-disk-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/v1_serviceaccount_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/hypershift_role.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/azure-disk/standalone/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_role_azure-disk-csi-driver-operator-role.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_rolebinding_azure-disk-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/v1_serviceaccount_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/standalone/kustomization.yaml
  assets/csidriveroperators/azure-disk/standalone/monitoring_role.patch.yaml
  hack/generate-manifests.sh
  manifests/10_deployment-hypershift.yaml
  pkg/operator/csidriveroperator/csioperatorclient/azure-disk.go
  pkg/operator/operator_starter.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#440 STOR-1354: Remove Alibaba Disk CSI Driver
  assets/csidriveroperators/alibaba-disk/02_sa.yaml
  assets/csidriveroperators/alibaba-disk/03_role.yaml
  assets/csidriveroperators/alibaba-disk/04_rolebinding.yaml
  assets/csidriveroperators/alibaba-disk/05_clusterrole.yaml
  assets/csidriveroperators/alibaba-disk/06_clusterrolebinding.yaml
  assets/csidriveroperators/alibaba-disk/07_deployment.yaml
  assets/csidriveroperators/alibaba-disk/08_cr.yaml
  manifests/03_credentials_request_alibaba.yaml
  manifests/10_deployment-hypershift.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/ibm-cloud-managed-cleanup.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/alibaba-disk.go
  pkg/operator/defaultstorageclass/controller.go
  pkg/operator/operator_starter.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#442 STOR-1289: Move vSphere prometheus rules to CSO
  assets/vsphere_problem_detector/12_prometheusrules.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#444 OCPBUGS-27159: Allow vSphere CSI driver to be disabled
  pkg/operator/csidriveroperator/csioperatorclient/vsphere.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#445 STOR-1611: remove ibm-vpc-node-label-updater
  assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
  manifests/10_deployment-hypershift.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/ibm-vpc-block.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
