Repository openshift/cluster-storage-operator, pull requests merged in 2024-12, with the labels that each got.

#545 STOR-2078: Add RBAC rule for Volumeattributesclass
  assets/csidriveroperators/aws-ebs/base/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#544 OCPBUGS-45737: Remove unecessary resources from the guest cluster
  assets/csidriveroperators/openstack-manila/base/02_sa.yaml
  assets/csidriveroperators/openstack-manila/base/03_role.yaml
  assets/csidriveroperators/openstack-manila/base/04_rolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_v1_serviceaccount_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_manila.csi.openstack.org.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/v1_serviceaccount_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_v1_serviceaccount_manila-csi-driver-operator.yaml
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#549 STOR-2078: Typo in clusterRole resources for VolumeAttributesClasses
  manifests/09_openshift-csi-provisioner-volumeattributesclass-reader-role.yaml
  manifests/09_openshift-csi-resizer-volumeattributesclass-reader-role.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference
