Repository openshift/cluster-storage-operator, pull requests merged in 2024-11, with the labels that each got.

#533 OCPBUGS-43767: Fix PodStartupStorageOperationsFailing alert
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#529 OCPBUGS-43794: add ability to control kube rbac proxy container image on controlplane
  assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  manifests/10_deployment-hypershift.yaml
  pkg/operator/csidriveroperator/util.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#534 STOR-2078: Add ClusterRole Volumeattributesclass for provisioner and resizer
  assets/csidriveroperators/aws-ebs/base/05_clusterrole.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  manifests/09_openshift-csi-provisioner-volumeattributesclass-reader-role.yaml
  manifests/09_openshift-csi-resizer-volumeattributesclass-reader-role.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#535 NO-JIRA: Add openstack-approvers to root OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#539 STOR-2078: Add var OPERATOR_IMAGE_VERSION
  assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#527 OSASINFRA-3635: Add manila csi to hypershift
  assets/csidriveroperators/openstack-manila/base/01_namespace.yaml
  assets/csidriveroperators/openstack-manila/base/02_sa.yaml
  assets/csidriveroperators/openstack-manila/base/03_role.yaml
  assets/csidriveroperators/openstack-manila/base/04_rolebinding.yaml
  assets/csidriveroperators/openstack-manila/base/05_clusterrole.yaml
  assets/csidriveroperators/openstack-manila/base/06_clusterrolebinding.yaml
  assets/csidriveroperators/openstack-manila/base/07_deployment.yaml
  assets/csidriveroperators/openstack-manila/base/08_cr.yaml
  assets/csidriveroperators/openstack-manila/base/kustomization.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/default_operator.openshift.io_v1_clustercsidriver_manila.csi.openstack.org.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/openshift-cluster-csi-drivers_v1_serviceaccount_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_manila-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_manila-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/generated/v1_namespace_openshift-manila-csi-driver.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/openstack-manila/hypershift/guest/monitoring_role.patch.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/apps_v1_deployment_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/v1_serviceaccount_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/hypershift_role.patch.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/sa.patch.yaml
  assets/csidriveroperators/openstack-manila/standalone/deployment.patch.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/default_operator.openshift.io_v1_clustercsidriver_manila.csi.openstack.org.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_apps_v1_deployment_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_role_manila-csi-driver-operator-role.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_rbac.authorization.k8s.io_v1_rolebinding_manila-csi-driver-operator-rolebinding.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_v1_serviceaccount_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_manila-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_manila-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/v1_namespace_openshift-manila-csi-driver.yaml
  assets/csidriveroperators/openstack-manila/standalone/kustomization.yaml
  assets/csidriveroperators/openstack-manila/standalone/monitoring_role.patch.yaml
  hack/generate-manifests.sh
  manifests/10_deployment-hypershift.yaml
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
  pkg/operator/operator_starter.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#531 NO-JIRA: Remove kustomize-related annotations from generated assets
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_ebs.csi.aws.com.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_aws-ebs-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/operator.openshift.io_v1_clustercsidriver_ebs.csi.aws.com.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_aws-ebs-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_aws-ebs-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/aws-ebs/standalone/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/operator.openshift.io_v1_clustercsidriver_disk.csi.azure.com.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-disk-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-disk-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-disk/standalone/kustomization.yaml
  assets/csidriveroperators/azure-file/hypershift/guest/generated/operator.openshift.io_v1_clustercsidriver_file.csi.azure.com.yaml
  assets/csidriveroperators/azure-file/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-file-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-file/hypershift/guest/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-file-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-file/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/azure-file/standalone/generated/operator.openshift.io_v1_clustercsidriver_file.csi.azure.com.yaml
  assets/csidriveroperators/azure-file/standalone/generated/rbac.authorization.k8s.io_v1_clusterrole_azure-file-csi-driver-operator-clusterrole.yaml
  assets/csidriveroperators/azure-file/standalone/generated/rbac.authorization.k8s.io_v1_clusterrolebinding_azure-file-csi-driver-operator-clusterrolebinding.yaml
  assets/csidriveroperators/azure-file/standalone/kustomization.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#542 STOR-2078: Add OPERATOR_IMAGE_VERSION var to AWS-EBS operator
  pkg/operator/csidriveroperator/csioperatorclient/aws.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
