Repository openshift/cluster-storage-operator, pull requests merged in 2024-07, with the labels that each got.

#485 STOR-1767: add env var OPERATOR_NAME to vsphere csi operator deployment
  assets/csidriveroperators/vsphere/08_deployment.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#484 [release-4.15] OCPBUGS-36374: Set required-scc for openshift workloads
  assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  manifests/10_deployment-hypershift.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#483 OCPBUGS-36169: deactivate MultipleDefaultStorageClasses alert immediately after being fixed
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, px-approved, docs-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#477 MON-2065: manifests: add k8s storage rules
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#487 STOR-1767: Disable vsphere-problem-detector alerts if ManagementState==Removed
  pkg/operator/vsphereproblemdetector/monitoring.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#495 OCPBUGS-37633: Add permissions for vsphere_problem_detector to access clustercsidrivers
  assets/vsphere_problem_detector/04_clusterrole.yaml
Labels: approved, lgtm, jira/severity-critical, jira/valid-bug, jira/valid-reference

#493 CNV-44992: HCP custom tolerations integration
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/hypershift_deployment_controller.go
  pkg/utils/deployment_controller.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
