Repository openshift/cluster-storage-operator, pull requests merged in 2024-10, with the labels that each got.

#512 NO-JIRA: release-4.16: Run make update
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#511 NO-JIRA: Always recreate manifests
  hack/generate-manifests.sh
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#513 NO-JIRA: Remove OLMOperatorRemovalController
  pkg/csoclients/csoclients.go
  pkg/operator/csidriveroperator/csioperatorclient/manila.go
  pkg/operator/csidriveroperator/csioperatorclient/types.go
  pkg/operator/csidriveroperator/deploymentcontroller.go
  pkg/operator/csidriveroperator/driver_starter.go
  pkg/operator/csidriveroperator/olmremovalcontroller.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#516 AUTH-482: set required-scc for openshift workloads
  assets/vsphere_problem_detector/07_deployment.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#515 OCPBUGS-41365: add ability to control kube rbac proxy container image…
  manifests/10_deployment-hypershift.yaml
  pkg/operator/csidriveroperator/util.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#518 OCPBUGS-41365: fix typo CONTROL_PLANE_KUBE_RBAC_PROXY_IMAGE -> KUBE_R…
  pkg/operator/csidriveroperator/util.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#519 NO-JIRA: assets: shared-resource: hypershift: add pull-secret to operator SA
  assets/csidriveroperators/shared-resource/hypershift/mgmt/02_sa.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#522 OCPBUGS-41365: add KUBE_RBAC_PROXY_CONTROL_PLANE_IMAGE to other neede…
  assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#517 HOSTEDCP-2033: Add ARO HCP environment vars to CSI deployment
  pkg/operator/csidriveroperator/hypershift_deployment_controller.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#509 STOR-1823: Remove shared-resource CSI driver from CSO
  assets/csidriveroperators/shared-resource/hypershift/guest/10_cr.yaml
  assets/csidriveroperators/shared-resource/hypershift/mgmt/02_sa.yaml
  assets/csidriveroperators/shared-resource/hypershift/mgmt/09_deployment.yaml
  assets/csidriveroperators/shared-resource/standalone/02_sa.yaml
  assets/csidriveroperators/shared-resource/standalone/03_role.yaml
  assets/csidriveroperators/shared-resource/standalone/04_rolebinding.yaml
  assets/csidriveroperators/shared-resource/standalone/05_clusterrole.yaml
  assets/csidriveroperators/shared-resource/standalone/06_clusterrolebinding.yaml
  assets/csidriveroperators/shared-resource/standalone/07_role_config.yaml
  assets/csidriveroperators/shared-resource/standalone/08_rolebinding_config.yaml
  assets/csidriveroperators/shared-resource/standalone/09_deployment.yaml
  assets/csidriveroperators/shared-resource/standalone/10_cr.yaml
  assets/csidriveroperators/shared-resource/standalone/11_metrics_service.yaml
  assets/csidriveroperators/shared-resource/standalone/12_servicemonitor.yaml
  manifests/10_deployment-hypershift.yaml
  manifests/10_deployment-ibm-cloud-managed.yaml
  manifests/10_deployment.yaml
  manifests/image-references
  pkg/operator/csidriveroperator/csioperatorclient/shared-resource.go
  pkg/operator/csidriveroperator/driver_starter_test.go
  pkg/operator/operator_starter.go
  profile-patches/hypershift/10_deployment.yaml-patch
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#526 NO-JIRA: Add README to assets + remove redundant definitions
  assets/csidriveroperators/README.md
  assets/csidriveroperators/aws-ebs/base/02_sa.yaml
  assets/csidriveroperators/aws-ebs/base/03_role.yaml
  assets/csidriveroperators/aws-ebs/base/09_deployment.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/claim_role.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/sa.patch.yaml
  assets/csidriveroperators/aws-ebs/standalone/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/base/08_deployment.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/claim_role.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/sa.patch.yaml
  assets/csidriveroperators/azure-disk/standalone/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/standalone/kustomization.yaml
  assets/csidriveroperators/azure-file/base/08_deployment.yaml
  assets/csidriveroperators/azure-file/hypershift/guest/kustomization.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/kustomization.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/sa.patch.yaml
  assets/csidriveroperators/azure-file/standalone/deployment.patch.yaml
  assets/csidriveroperators/azure-file/standalone/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference

#530 HOSTEDCP-2033: Correct ARO HCP environment vars for CSI driver operator deployment
  pkg/operator/csidriveroperator/hypershift_deployment_controller.go
Labels: approved, lgtm, tide/merge-method-squash, qe-approved, px-approved, docs-approved, jira/valid-reference

#524 AUTH-482: set required-scc for openshift workloads
  assets/csidriveroperators/azure-disk/base/08_deployment.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/standalone/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file-original/08_deployment.yaml
  assets/csidriveroperators/azure-file/base/08_deployment.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/standalone/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  assets/csidriveroperators/gcp-pd/07_deployment.yaml
  assets/csidriveroperators/ibm-vpc-block/08_deployment.yaml
  assets/csidriveroperators/manila/07_deployment.yaml
  assets/csidriveroperators/openstack-cinder/07_deployment.yaml
  assets/csidriveroperators/ovirt/07_deployment.yaml
  assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
  assets/csidriveroperators/powervs-block/standalone/06_deployment.yaml
  assets/csidriveroperators/vsphere/08_deployment.yaml
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-reference
