Repository openshift/cluster-storage-operator, pull requests merged in 2025-08, with the labels that each got.

#602 STOR-2330: Add RBAC rule to let ibm-vpc-block-csi-driver-operator manage NetworkPolicy
  assets/csidriveroperators/ibm-vpc-block/04_role.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#601 STOR-2330: Add labels to subscribe openstack cinder and manila CSI driver operators to NPs
  assets/csidriveroperators/openstack-cinder/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/openstack-cinder/hypershift/mgmt/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-cinder/standalone/deployment.patch.yaml
  assets/csidriveroperators/openstack-cinder/standalone/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/openstack-manila/hypershift/mgmt/generated/apps_v1_deployment_manila-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-manila/standalone/deployment.patch.yaml
  assets/csidriveroperators/openstack-manila/standalone/generated/openshift-cluster-csi-drivers_apps_v1_deployment_manila-csi-driver-operator.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#603 OCPBUGS-60064: hypershift: add app label to csdriveroperators running in HCP
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-disk/hypershift/mgmt/generated/apps_v1_deployment_azure-disk-csi-driver-operator.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/azure-file/hypershift/mgmt/generated/apps_v1_deployment_azure-file-csi-driver-operator.yaml
  assets/csidriveroperators/openstack-cinder/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/openstack-cinder/hypershift/mgmt/generated/apps_v1_deployment_openstack-cinder-csi-driver-operator.yaml
  assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#600 STOR-2330: Add labels to subscribe ibm-powervs-block CSI driver operator to NPs
  assets/csidriveroperators/powervs-block/hypershift/mgmt/06_deployment.yaml
  assets/csidriveroperators/powervs-block/standalone/06_deployment.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#607 STOR-2549: Remove TP label from VAP files
  manifests/13_validating_admission_policy.yaml
  manifests/14_validating_admission_policy_binding.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#609 OCPBUGS-60948: Rename the SELinuxMount metric to :count
  manifests/12_prometheusrules.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
