Repository openshift/cluster-storage-operator, pull requests merged in 2025-03, with the labels that each got.

#528 CFE-1131: Added token minter Sidecar for aws-ebs hypershift-deployments
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/deployment.patch.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/generated/apps_v1_deployment_aws-ebs-csi-driver-operator.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/hypershift_token_minter.yaml
  assets/csidriveroperators/aws-ebs/hypershift/mgmt/kustomization.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#560 [release-4.17] OCPBUGS-52222: fix Vsphere cluster Storage operator in Unavailable state
  pkg/operator/operator_starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#566 OCPBUGS-24588: bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/deploymentcontroller/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#568 NO-JIRA: NO-JIRA: Remove bertinatto from OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, qe-approved, jira/valid-reference
